[tool.poetry]
name = "kydux"
version = "0.1.0"
description = ""
authors = ["Theia Vogel <theia@vgel.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11"
repeng = "^0.3.1"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
